// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCCl05RpMkJKoT_jOa8oM9K6y6C1zzIg',
    appId: '1:129414579832:web:d171f0d7a1681a29e78f8d',
    messagingSenderId: '129414579832',
    projectId: 'eve-nage',
    authDomain: 'eve-nage.firebaseapp.com',
    storageBucket: 'eve-nage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlz4FqpMph36MfxrM9Vyx4z5kQE75zaI',
    appId: '1:129414579832:android:0de4e0f145cc7205e78f8d',
    messagingSenderId: '129414579832',
    projectId: 'eve-nage',
    storageBucket: 'eve-nage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTpa0imQYvaeeQbWJDlILkxqL2VX3Rt4',
    appId: '1:129414579832:ios:cc4420760c6bc62be78f8d',
    messagingSenderId: '129414579832',
    projectId: 'eve-nage',
    storageBucket: 'eve-nage.firebasestorage.app',
    iosBundleId: 'com.example.evenage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTpa0imQYvaeeQbWJDlILkxqL2VX3Rt4',
    appId: '1:129414579832:ios:cc4420760c6bc62be78f8d',
    messagingSenderId: '129414579832',
    projectId: 'eve-nage',
    storageBucket: 'eve-nage.firebasestorage.app',
    iosBundleId: 'com.example.evenage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCCl05RpMkJKoT_jOa8oM9K6y6C1zzIg',
    appId: '1:129414579832:web:80b06404d9230db6e78f8d',
    messagingSenderId: '129414579832',
    projectId: 'eve-nage',
    authDomain: 'eve-nage.firebaseapp.com',
    storageBucket: 'eve-nage.firebasestorage.app',
  );
}